package com.offtamil.aitaskmanager

import android.content.*
import android.net.Uri
import android.os.Bundle
import androidx.activity.ComponentActivity
import androidx.activity.compose.setContent
import androidx.activity.compose.rememberLauncherForActivityResult
import androidx.activity.result.contract.ActivityResultContracts
import androidx.compose.foundation.background
import androidx.compose.foundation.clickable
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.lazy.items
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.filled.*
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Brush
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.platform.LocalContext
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import androidx.core.content.FileProvider
import org.json.JSONObject
import java.io.*
import java.text.SimpleDateFormat
import java.util.*
import java.util.zip.*

private val BG=Color(0xFF070A12); private val CARD=Color(0xFF101725); private val CYAN=Color(0xFF26D9FF); private val PURPLE=Color(0xFF8B5CFF); private val GREEN=Color(0xFF31E59A)
private data class Project(val id:String,val name:String,val date:String,val text:String,val files:Int,val dir:File)

class LauncherActivity:ComponentActivity(){
 override fun onCreate(b:Bundle?){super.onCreate(b);setContent{App()};if(b==null) capture(intent)}
 override fun onNewIntent(i:Intent){super.onNewIntent(i);capture(i)}
 private fun capture(i:Intent?){if(i?.action!=Intent.ACTION_SEND&&i?.action!=Intent.ACTION_SEND_MULTIPLE)return;val text=i.getStringExtra(Intent.EXTRA_TEXT).orEmpty();val uri=i.getParcelableExtra<Uri>(Intent.EXTRA_STREAM);if(text.isNotBlank()||uri!=null)Store.create(this,"Shared AI Chat",text,listOfNotNull(uri))}
}

@Composable private fun App(){val c=LocalContext.current;var tick by remember{mutableIntStateOf(0)};var page by remember{mutableIntStateOf(0)};var picked by remember{mutableStateOf<Project?>(null)};var create by remember{mutableStateOf(false)};var import by remember{mutableStateOf(false)};val projects=remember(tick){Store.list(c)};val picker=rememberLauncherForActivityResult(ActivityResultContracts.OpenDocument()){u->if(u!=null){Store.importZip(c,u);tick++}}
 MaterialTheme(colorScheme=darkColorScheme(background=BG,surface=CARD,primary=CYAN)){Surface(Modifier.fillMaxSize(),color=BG){when{picked!=null->Detail(picked!!,{picked=null});create->Create({create=false},{Store.create(c,it.first,it.second,emptyList());create=false;tick++});import->Import({import=false}){picker.launch(arrayOf("application/zip","application/octet-stream"))};else->Scaffold(containerColor=BG,bottomBar={Nav(page){page=it}}){p->Column(Modifier.fillMaxSize().padding(p)){Header();when(page){0->Home(projects,{create=true},{import=true}){picked=it};1->Projects(projects){picked=it};2->Transfer(projects){picked=it};else->Settings()}}}}}}}}

@Composable private fun Header(){Row(Modifier.fillMaxWidth().padding(18.dp),verticalAlignment=Alignment.CenterVertically){Box(Modifier.size(44.dp).background(Brush.linearGradient(listOf(PURPLE,CYAN)),RoundedCornerShape(14.dp)),contentAlignment=Alignment.Center){Icon(Icons.Default.AutoAwesome,null,tint=Color.White)};Spacer(Modifier.width(12.dp));Column{Text("AI Task Manager",fontSize=21.sp,fontWeight=FontWeight.Bold);Text("Save • Transfer • Continue",color=Color(0xFF8997AA),fontSize=12.sp)}}}
@Composable private fun Home(ps:List<Project>,new:()->Unit,imp:()->Unit,open:(Project)->Unit){LazyColumn(Modifier.fillMaxSize(),contentPadding=PaddingValues(18.dp),verticalArrangement=Arrangement.spacedBy(14.dp)){item{Column(Modifier.fillMaxWidth().background(Brush.linearGradient(listOf(Color(0xFF171D38),Color(0xFF0B2835))),RoundedCornerShape(25.dp)).padding(22.dp)){Text("Your AI work,",fontSize=27.sp,fontWeight=FontWeight.Bold);Text("always portable.",fontSize=27.sp,fontWeight=FontWeight.Bold,color=CYAN);Spacer(Modifier.height(8.dp));Text("AI → Share → Save → Export → Another AI",color=Color(0xFF9AA8BB));Spacer(Modifier.height(15.dp));Row(horizontalArrangement=Arrangement.spacedBy(8.dp)){Pill("NO API",CYAN);Pill("ONE TAP",GREEN);Pill("LOCAL",PURPLE)}}};item{Row(Modifier.fillMaxWidth(),horizontalArrangement=Arrangement.spacedBy(10.dp)){CardButton("Capture","Share from any AI",Icons.Default.Share,CYAN,Modifier.weight(1f),new);CardButton("Import","Checkpoint ZIP",Icons.Default.FileDownload,GREEN,Modifier.weight(1f),imp)}};item{Text("Recent projects",fontSize=18.sp,fontWeight=FontWeight.Bold)};items(ps.take(10),key={it.id}){RowItem(it,open)}}}
@Composable private fun Projects(ps:List<Project>,open:(Project)->Unit){LazyColumn(Modifier.fillMaxSize(),contentPadding=PaddingValues(18.dp),verticalArrangement=Arrangement.spacedBy(10.dp)){item{Text("My Projects",fontSize=25.sp,fontWeight=FontWeight.Bold);Text("Every captured chat becomes a portable checkpoint.",color=Color(0xFF8997AA),modifier=Modifier.padding(top=4.dp,bottom=8.dp))};items(ps,key={it.id}){RowItem(it,open)}}}
@Composable private fun Transfer(ps:List<Project>,open:(Project)->Unit){LazyColumn(Modifier.fillMaxSize(),contentPadding=PaddingValues(18.dp),verticalArrangement=Arrangement.spacedBy(12.dp)){item{Text("Transfer",fontSize=25.sp,fontWeight=FontWeight.Bold);Text("Move a checkpoint between AI apps with the Android share sheet.",color=Color(0xFF8997AA))};item{Info("FLOW",listOf("Capture from Claude / ChatGPT / Gemini / any AI","Keep chat + shared files locally","Export one ZIP checkpoint","Share it to another AI app"))};items(ps,key={it.id}){RowItem(it,open)}}}
@Composable private fun Settings(){Column(Modifier.fillMaxSize().padding(18.dp)){Text("Settings",fontSize=25.sp,fontWeight=FontWeight.Bold);Spacer(Modifier.height(12.dp));Info("LOCAL-FIRST",listOf("No AI credentials stored","No provider API keys required","Files remain in app storage","Android Sharesheet handles transfer"))}}
@Composable private fun Create(back:()->Unit,done:(Pair<String,String>)->Unit){val c=LocalContext.current;var n by remember{mutableStateOf("")};var t by remember{mutableStateOf("")};Column(Modifier.fillMaxSize().padding(18.dp)){Title("New Checkpoint",back);Spacer(Modifier.height(12.dp));OutlinedTextField(n,{n=it},Modifier.fillMaxWidth(),label={Text("Project name")},singleLine=true);Spacer(Modifier.height(12.dp));OutlinedTextField(t,{t=it},Modifier.fillMaxWidth().height(190.dp),label={Text("Chat / context")});Spacer(Modifier.height(16.dp));Button({done((n.ifBlank{"AI Project"}) to t)},Modifier.fillMaxWidth().height(54.dp),colors=ButtonDefaults.buttonColors(containerColor=PURPLE)){Icon(Icons.Default.Save,null);Spacer(Modifier.width(7.dp));Text("Save Checkpoint")};Text("Fastest capture: open an AI chat → Share → AI Task Manager.",color=Color(0xFF77869B),fontSize=12.sp,modifier=Modifier.padding(top=10.dp))}}
@Composable private fun Import(back:()->Unit,pick:()->Unit){Column(Modifier.fillMaxSize().padding(18.dp)){Title("Import Checkpoint",back);Spacer(Modifier.height(25.dp));Box(Modifier.fillMaxWidth().height(250.dp).background(CARD,RoundedCornerShape(24.dp)),contentAlignment=Alignment.Center){Column(horizontalAlignment=Alignment.CenterHorizontally){Icon(Icons.Default.FolderZip,null,tint=CYAN,modifier=Modifier.size(55.dp));Spacer(Modifier.height(10.dp));Text("Restore portable ZIP",fontSize=20.sp,fontWeight=FontWeight.Bold);Text("Chat + files + metadata",color=Color(0xFF8997AA));Spacer(Modifier.height(18.dp));Button(pick){Icon(Icons.Default.FileOpen,null);Spacer(Modifier.width(6.dp));Text("Choose ZIP")}}}}}
@Composable private fun Detail(p:Project,back:()->Unit){val c=LocalContext.current;Column(Modifier.fillMaxSize().padding(18.dp)){Title(p.name,back);Spacer(Modifier.height(10.dp));Row(horizontalArrangement=Arrangement.spacedBy(8.dp)){Pill("CHECKPOINT",GREEN);Pill("LOCAL",PURPLE)};Spacer(Modifier.height(12.dp));Info("PROJECT",listOf("Captured ${p.date}","${p.files} attachment(s)","${p.text.length} characters","Ready to continue"));Spacer(Modifier.height(12.dp));Text("Chat / Context",fontSize=18.sp,fontWeight=FontWeight.Bold);Spacer(Modifier.height(7.dp));Box(Modifier.fillMaxWidth().weight(1f).background(CARD,RoundedCornerShape(18.dp)).padding(15.dp)){LazyColumn{item{Text(p.text.ifBlank{"No text captured."},color=Color(0xFFD4DCEA))}}};Spacer(Modifier.height(12.dp));Row(Modifier.fillMaxWidth(),horizontalArrangement=Arrangement.spacedBy(10.dp)){OutlinedButton({Store.share(c,p)},Modifier.weight(1f).height(52.dp)){Icon(Icons.Default.Share,null);Spacer(Modifier.width(5.dp));Text("Share")};Button({Store.export(c,p)},Modifier.weight(1f).height(52.dp),colors=ButtonDefaults.buttonColors(containerColor=PURPLE)){Icon(Icons.Default.FileDownload,null);Spacer(Modifier.width(5.dp));Text("Export ZIP")}}}}
@Composable private fun RowItem(p:Project,open:(Project)->Unit){Row(Modifier.fillMaxWidth().background(CARD,RoundedCornerShape(17.dp)).clickable{open(p)}.padding(15.dp),verticalAlignment=Alignment.CenterVertically){Box(Modifier.size(43.dp).background(Brush.linearGradient(listOf(PURPLE,CYAN)),RoundedCornerShape(13.dp)),contentAlignment=Alignment.Center){Text("AI",color=Color.White,fontWeight=FontWeight.Bold)};Spacer(Modifier.width(12.dp));Column(Modifier.weight(1f)){Text(p.name,fontWeight=FontWeight.SemiBold);Text("${p.date} • ${p.files} files",color=Color(0xFF7F8DA2),fontSize=11.sp);Text(p.text.replace("\n"," ").take(70),color=Color(0xFFB2BDCC),fontSize=12.sp,maxLines=1)};Icon(Icons.Default.ChevronRight,null,tint=Color(0xFF65748A))}}
@Composable private fun CardButton(a:String,b:String,ic:androidx.compose.ui.graphics.vector.ImageVector,t:Color,m:Modifier,on:()->Unit){Column(m.background(CARD,RoundedCornerShape(18.dp)).clickable{on()}.padding(15.dp)){Icon(ic,null,tint=t,modifier=Modifier.size(27.dp));Spacer(Modifier.height(9.dp));Text(a,fontWeight=FontWeight.Bold);Text(b,color=Color(0xFF8190A4),fontSize=11.sp)}}
@Composable private fun Info(title:String,lines:List<String>){Column(Modifier.fillMaxWidth().background(CARD,RoundedCornerShape(20.dp)).padding(16.dp)){Text(title,fontWeight=FontWeight.Bold);Spacer(Modifier.height(8.dp));lines.forEach{Row(Modifier.padding(vertical=4.dp)){Icon(Icons.Default.CheckCircle,null,tint=GREEN,modifier=Modifier.size(16.dp));Spacer(Modifier.width(8.dp));Text(it,color=Color(0xFFB8C3D3),fontSize=12.sp)}}}}
@Composable private fun Pill(s:String,c:Color){Surface(color=c.copy(alpha=.12f),shape=RoundedCornerShape(50)){Text(s,color=c,fontSize=9.sp,fontWeight=FontWeight.Bold,modifier=Modifier.padding(horizontal=9.dp,vertical=5.dp))}}
@Composable private fun Title(s:String,back:()->Unit){Row(verticalAlignment=Alignment.CenterVertically){IconButton(back){Icon(Icons.Default.ArrowBack,"Back")};Text(s,fontSize=23.sp,fontWeight=FontWeight.Bold)}}
@Composable private fun Nav(sel:Int,set:(Int)->Unit){NavigationBar(containerColor=Color(0xFF090D17)){listOf("Home" to Icons.Default.Home,"Projects" to Icons.Default.Folder,"Transfer" to Icons.Default.SwapHoriz,"Settings" to Icons.Default.Settings).forEachIndexed{i,(s,ic)->NavigationBarItem(sel==i,{set(i)},{Icon(ic,null)},{Text(s,fontSize=10.sp)})}}}

private object Store{
 private fun root(c:Context)=File(c.filesDir,"projects").apply{mkdirs()}
 fun list(c:Context)=root(c).listFiles()?.filter{it.isDirectory}.mapNotNull{read(it)}?.sortedByDescending{it.dir.lastModified()}?:emptyList()
 private fun read(d:File)=try{val j=JSONObject(File(d,"metadata.json").readText());Project(j.getString("id"),j.getString("name"),j.getString("date"),File(d,"chat.txt").takeIf{it.exists()}?.readText().orEmpty(),d.resolve("attachments").listFiles()?.size?:0,d)}catch(_:Exception){null}
 fun create(c:Context,name:String,text:String,uris:List<Uri>){val id="p_"+System.currentTimeMillis();val d=File(root(c),id);val a=File(d,"attachments");a.mkdirs();File(d,"chat.txt").writeText(text);uris.forEachIndexed{i,u->try{c.contentResolver.openInputStream(u)?.use{input->FileOutputStream(File(a,"attachment_$i")).use{out->input.copyTo(out)}}}catch(_:Exception){}};val date=SimpleDateFormat("yyyy-MM-dd HH:mm",Locale.US).format(Date());File(d,"metadata.json").writeText(JSONObject().put("id",id).put("name",name).put("date",date).toString(2));File(d,"instructions.md").writeText("Continue from this checkpoint. Inspect the supplied chat/context and files. Do not redo completed work.")}
 private fun zip(c:Context,p:Project):File{val f=File(c.cacheDir,p.id+".zip");ZipOutputStream(BufferedOutputStream(FileOutputStream(f))).use{z->p.dir.walkTopDown().filter{it.isFile}.forEach{x->z.putNextEntry(ZipEntry(p.dir.toPath().relativize(x.toPath()).toString()));x.inputStream().use{it.copyTo(z)};z.closeEntry()}};return f}
 fun export(c:Context,p:Project)=shareFile(c,zip(c,p));fun share(c:Context,p:Project)=shareFile(c,zip(c,p))
 private fun shareFile(c:Context,f:File){val u=FileProvider.getUriForFile(c,"com.offtamil.aitaskmanager.files",f);val i=Intent(Intent.ACTION_SEND).apply{type="application/zip";putExtra(Intent.EXTRA_STREAM,u);putExtra(Intent.EXTRA_TEXT,"AI Task checkpoint. Open/restore this ZIP, inspect the included context and files, then continue the task from the checkpoint.");addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION)};c.startActivity(Intent.createChooser(i,"Share checkpoint to AI"))}
 fun importZip(c:Context,u:Uri){try{val id="import_"+System.currentTimeMillis();val d=File(root(c),id);d.mkdirs();ZipInputStream(BufferedInputStream(c.contentResolver.openInputStream(u)!!)).use{z->var e=z.nextEntry;while(e!=null){val out=File(d,e.name).canonicalFile;if(!out.path.startsWith(d.canonicalPath+File.separator)){e=z.nextEntry;continue};if(e.isDirectory)out.mkdirs()else{out.parentFile?.mkdirs();FileOutputStream(out).use{z.copyTo(it)}};z.closeEntry();e=z.nextEntry}};if(!File(d,"metadata.json").exists())File(d,"metadata.json").writeText(JSONObject().put("id",id).put("name","Imported Checkpoint").put("date",SimpleDateFormat("yyyy-MM-dd HH:mm",Locale.US).format(Date())).toString(2))}catch(_:Exception){}}
}
